spring:
  application:
    name: gateway-client-service
  profiles:
    active: prod    

server:
  port: ${port}
  
eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${url}
      
---
spring:
    profiles: devLocal
port: 7111
portEureka: 8761
hostName: localhost
url: http://${hostName}:${portEureka}/eureka/
---
spring:
    profiles: prod
port: 7111
url: http://eureka:8761/eureka/
