spring:
  application:
    name: gateway-api-service

server:
  port: ${port}
  
eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${url}
      
---
spring:
    profiles: devLocal
port: 7111
portEureka: 8761
hostName: localhost
url: http://${hostName}:${portEureka}/eureka/
    
