version: '2'
services:
  postgres:
    container_name: gateway-postgres-poc
    build: ./postgres
    image: gateway-postgres-poc-image:1
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432

