spring:
  application:
    name: gateway-consumer
  profiles:
    active: prod
    
server:
  port: ${port}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${url}

zuul:
  routes:
      api:
        url: http://${hostName}:${port}

gateway-server:
  ribbon:
    #eureka:
    #  enabled: true
    DeploymentContextBasedVipAddresses: gateway-client-service
   # listOfServers: localhost:7111,localhost:9999
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    ServerListRefreshInterval: 10000
   
---
spring:
    profiles: devLocal
port: 8002
portEureka: 8761
hostName: localhost
url: http://${hostName}:${portEureka}/eureka/
---
spring:
    profiles: prod
port: 8002
portEureka: 8761
hostName: eureka
url: http://eureka:8761/eureka/