apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30761
  selector:
    app: eureka
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: docker.io/accurateriopreto/eureka:0.0.3
          ports:
            - containerPort: 8761
