apiVersion: v1
kind: Service
metadata:
  name: gateway-client-service
  labels:
    app: gateway-client-service
spec:
  type: NodePort
  ports:
    - port: 7111
      targetPort: 7111
      nodePort: 30111
  selector:
    app: gateway-client-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-client-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-client-service
    spec:
      containers:
        - name: eureka
          image: docker.io/accurateriopreto/gateway-client-service:0.0.10
          ports:
            - containerPort: 7111
