apiVersion: v1
kind: Service
metadata:
  name: gateway-consumer
  labels:
    app: gateway-consumer
spec:
  type: NodePort
  ports:
    - port: 8002
      targetPort: 8002
      nodePort: 30802
  selector:
    app: gateway-consumer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-consumer
    spec:
      containers:
        - name: gateway-consumer
          image: docker.io/accurateriopreto/gateway-consumer:0.0.5
          ports:
            - containerPort: 8002
