apiVersion: v1
kind: Service
metadata:
  name: postgres-poc-test
  labels:
    app: postgres-poc-test
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 32760
  selector:
    app: postgres-poc-test
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-poc-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-poc-test
    spec:
      containers:
        - name: postgres-poc-test
          image: docker.io/accurateriopreto/gateway-postgres-poc-image:1
          ports:
            - containerPort: 5432
